[자동차 경주] 박정은 미션 제출합니다.
woowacourse-precourse/java-racingcar-7 pull request #585
Opened 2024-10-27 18:11 UTC by eeun1225

2024-10-31 13:59 UTC, eaststar113 requested changes
전반적으로 코드가 깔끔해서 이해하고 읽기 쉬웠습니다. 패키지 분리도 기능별로 확실하게 나누신거 같아 기능 책임 분리에 고민과 노력 많이 하신거 같습니다!

다만 개인적인 생각으로 아쉬웠던 부분은 예외처리의 경우의 수가 조금 더 있지 않을까라는 생각이 들었습니다. 또 예외처리 과정에서 어떤 경우의 예외처리인지도 구분이 명확하면 사용자 입장에서 더 이해하기 쉬운 프로그램이 되지않을까라고 생각이 들었습니다.

config사용이나 객체별로 확실하게 나누신 부분은 오히려 제가 배워가는 부분이였습니다. 좋은 코드 잘 보고 갑니다~!

2주차 고생많으셨고 3주차도 같이 파이팅해요..!

2024-10-31 13:59 UTC, eaststar113 commented on src/main/java/racingcar/AppConfig.java
> +public class AppConfig {
config활용은 잘몰라서 사용해본적이 없는데 코드 전반적으로 훨씬 깔끔해보여서 좋은거같아요..!

2024-10-31 13:59 UTC, eaststar113 commented on src/main/java/racingcar/io/Input.java
> +        System.out.println("경주할 자동차 이름을 입력하세요.(이름은 쉼표(,) 기준으로 구분)");
문자열 같은 경우는 따로 클래스를 만들어서 관리하는것도 좋을 거 같습니다!

2024-10-31 13:59 UTC, eaststar113 commented on src/main/java/racingcar/io/Output.java
> +        String winner = String.join(", ", winners);
쉼표도 상수화하면 더 깔끔하고 좋을 거 같아요..!

2024-10-31 13:59 UTC, eaststar113 commented on src/main/java/racingcar/validation/ValidateInput.java
> +    }
예외처리 문구들도 경우마다 설정하면 더 가독성 있을 거 같다고 생각합니다!

2024-11-01 01:56 UTC, koosco commented on src/main/java/racingcar/io/Input.java
> +        System.out.println("경주할 자동차 이름을 입력하세요.(이름은 쉼표(,) 기준으로 구분)");
재사용되지 않을 것 같은 문자열인데 클래스를 만들어서 관리하는 이유가 궁금해요

2024-11-01 02:12 UTC, koosco reviewed
2주차 고생 많으셨습니다~
3주차에는 의존성을 줄이는 과제가 있으니 객체간 의존성에 대해 더 고민해보셔도 좋을 것 같아요!
다음주도 화이팅 하세요 :)

2024-11-01 02:12 UTC, koosco commented on src/main/java/racingcar/racing/RacingManager.java
> +        System.out.println("실행결과");
출력 책임을 분리해도 좋을 것 같아요

2024-11-01 02:12 UTC, koosco commented on src/main/java/racingcar/racing/RacingManager.java
> +    private final Output output;
Manager에서 Output 의존성은 불필요한 결합도를 높일 수도 있을 것 같아요

2024-11-01 02:12 UTC, koosco commented on src/main/java/racingcar/racing/RoundRace.java
> +        for(Car car : cars) {
Car 내에서 움직이는 로직을 포함시키는 것이 캡슐화를 높일 수 있지 않을까요? 변경에 취약해지거나 중복 코드가 발생할 위험이 생길 것 같아요

2024-11-01 02:12 UTC, koosco commented on src/main/java/racingcar/racing/Winner.java
> +    public int findMaxPosition(List<Car> cars) {
private으로 감춰도 되지 않을까요?

2024-11-01 02:12 UTC, koosco commented on src/main/java/racingcar/validation/ValidateInput.java
> +    }
재밌게 요구사항을 만족시킨 것 같아요. 던지는 예외가 달라질 때는 쓰기 어려울 것 같아요 😂

2024-11-01 02:12 UTC, koosco commented on src/main/java/racingcar/validation/ValidateInput.java
> +        if (input.trim().isEmpty()) {
isBlank 사용은 어떤가요?

2024-11-01 02:12 UTC, koosco commented on src/main/java/racingcar/validation/ValidateInput.java
> +            if (car.length() > 5 || car.isEmpty() || car.contains(" ")) {
매직 넘버 상수 처리해도 좋을 것 같아요

2024-11-01 02:12 UTC, koosco commented on src/main/java/racingcar/validation/ValidateInput.java
> +            if (car.length() > 5 || car.isEmpty() || car.contains(" ")) {
isBlank로 한 번에 처리할 수 있을 것 같습니다

2024-11-01 06:05 UTC, eeun1225 commented on src/main/java/racingcar/racing/RoundRace.java
> +        for(Car car : cars) {
좋은 피드백 감사합니다! 
말씀하신 대로 Car 클래스 내에 움직임 로직을 포함시키는 것이 캡슐화 측면에서 더 유리할 것 같네요!!

2024-11-01 06:07 UTC, eeun1225 commented on src/main/java/racingcar/validation/ValidateInput.java
> +            if (car.length() > 5 || car.isEmpty() || car.contains(" ")) {
감사합니다! isBlank는 생각 못했던 것 같아요..! 앞으로 입력 검증이나 문자열 처리 로직에서 적극적으로 활용해서 코드가 더 명확하고 간결해지도록 해보겠습니다!!

2024-11-01 06:08 UTC, eeun1225 commented on src/main/java/racingcar/validation/ValidateInput.java
> +    }
감사합니다! 예외처리에 대해서 더 깊게 고려해보겠습니다!

2024-11-01 06:09 UTC, eeun1225 commented on src/main/java/racingcar/io/Output.java
> +        String winner = String.join(", ", winners);
좋은 피드백 감사합니다! 말씀하신 대로 쉼표나 숫자를 상수로 선언해서 사용하는게 더 좋을 것 같네요!!

2024-11-01 06:12 UTC, eeun1225 commented on src/main/java/racingcar/io/Input.java
> +        System.out.println("경주할 자동차 이름을 입력하세요.(이름은 쉼표(,) 기준으로 구분)");
입력받는 기능들을 모두 Input 클래스에서 관리하려는 의도로 작성했습니다! 
아직 재사용을 염두에 두진 않았지만, 입력 관련 로직을 한곳에서 처리하면 코드의 일관성과 관리가 더 쉬워질 거라 생각했어요. 
필요할 때마다 확장하거나 수정하기도 좋을 것 같고요. 그런데 재사용 문제까지는 생각하지 못했던 것 같아요🥺
피드백 감사합니다!

2024-11-05 04:53 UTC, Starlight258 reviewed
간단하게 코멘트 남겼습니다 :)

2024-11-05 04:53 UTC, Starlight258 commented on src/main/java/racingcar/racing/Winner.java
> +        return maxPosition;
`stream`을 이용해 `Collections.max()`를 사용해서 최대값을 구하는 방법도 있어요.

2024-11-05 04:53 UTC, Starlight258 commented on src/main/java/racingcar/io/Output.java
> +            System.out.print(car.getName() + " : " + "-".repeat(car.getPosition()));
`"-".repeat(car.getPosition()`는 단순 출력을 넘어서 메세지를 의미하고 있어요.
만약 console이 아닌 file로 출력해야한다면 해당 부분을 다시 구현해야할까요? `view`가 순수하게 출력만 담당하도록 만드는 것을 추천드려요.

2024-11-05 04:53 UTC, Starlight258 commented on src/main/java/racingcar/io/Input.java
> +        System.out.println("시도할 횟수는 몇 회인가요?");
해당 출력 부분도 Output로 추출하는 것이 어떨까요?

2026-05-25 07:10 UTC, closed without merging